<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_door_logout</name>
   <tag></tag>
   <elementGuidId>85bd44cf-0bc9-4a26-981f-72c6afad7d68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*/header/div[2]/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*/header/div[2]/div[3]/div</value>
      <webElementGuid>956976a0-ba7f-44f8-9905-c49f36dcf628</webElementGuid>
   </webElementProperties>
</WebElementEntity>
