<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NDINestle Indonesia</name>
   <tag></tag>
   <elementGuidId>1255aaf1-eae7-44c1-9444-3a4c3bf602a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnschema4 > div > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='btnschema4']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>08556b9c-8bdd-4aaa-a354-2961bde16cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NDINestle Indonesia</value>
      <webElementGuid>7621906e-24ef-42f6-936d-3f5a11ef6fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnschema4&quot;)/div[1]/div[1]</value>
      <webElementGuid>24b25674-008a-4181-8486-6e48e4ee0378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1bbb7cf6-9cbd-440e-8a23-7de8ca754d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NDINestle Indonesia</value>
      <webElementGuid>571afdf1-e23a-4395-974e-2ddd3f9fcc7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnschema4&quot;)/div[1]/div[1]</value>
      <webElementGuid>3870e7f0-ebdb-40f7-97fb-e0fa1935b08a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='btnschema4']/div/div</value>
      <webElementGuid>d1c1aa54-2a63-4e33-bd66-d6b6b2530801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asia Sakti Wahid Foods Manufacturing'])[1]/following::div[4]</value>
      <webElementGuid>cbc79cb3-bf2c-4b8a-bac8-72b1f35f5518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ASW'])[1]/following::div[5]</value>
      <webElementGuid>fb172219-3b57-4291-ab4a-f4aecda40550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div</value>
      <webElementGuid>8027b439-1aa4-4b62-8db3-0d5a82c4e45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'NDINestle Indonesia' or . = 'NDINestle Indonesia')]</value>
      <webElementGuid>38c7be95-19df-4de5-8160-86c9ac22821b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
