<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Logout from Nexchief Account</name>
   <tag></tag>
   <elementGuidId>bf054c53-1188-47be-8361-64ce767c0f1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnlogout > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnlogout']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>58142eeb-de00-4039-b2eb-ab3f90230961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout from Nexchief Account</value>
      <webElementGuid>e8b0c2c0-90d5-4886-bed2-8b1478206928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnlogout&quot;)/span[1]</value>
      <webElementGuid>31c7a6fb-05c7-4506-9340-3b3ce920dcf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btnlogout']/span</value>
      <webElementGuid>028d5047-555c-454e-bfdd-a19184ec27a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to Portal'])[1]/following::span[1]</value>
      <webElementGuid>f62191a4-1a2e-4be6-b2d1-a7df21f0d1a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure want to logout from the application?'])[1]/following::span[2]</value>
      <webElementGuid>b48f2680-a984-4f93-b5da-055828af7416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>55656841-25af-4e3a-8c39-9e23f9bbfaae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Logout from Nexchief Account' or . = 'Logout from Nexchief Account')]</value>
      <webElementGuid>2b10ba87-df7f-4100-b5fe-af7f5b24c88e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
