<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_edit_icon</name>
   <tag></tag>
   <elementGuidId>bef47b26-05a9-466e-b3bf-c547a09f49e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;editicon&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;editicon&quot;]</value>
      <webElementGuid>061f8eaf-d1c5-4bf5-9a07-4e1bae1918e0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
