<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_detail_icon</name>
   <tag></tag>
   <elementGuidId>84071d89-479c-437e-aaad-5c7828682459</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;detailicon&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;detailicon&quot;]</value>
      <webElementGuid>e27fe538-7899-441f-ac94-bffd286ddf3f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
