<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_pagination_item</name>
   <tag></tag>
   <elementGuidId>edaea6c0-31a7-4c5c-b67c-2bceab863184</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;btnpaginationreason&quot;]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;btnpaginationreason&quot;]/ul/li/a</value>
      <webElementGuid>3986747e-c500-4c24-a6f9-da96043ecc1d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
