<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_back_to_list</name>
   <tag></tag>
   <elementGuidId>19518e70-f8bd-4771-9da7-e6be8ea474ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;btnback&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;btnback&quot;]</value>
      <webElementGuid>d882963c-f5c3-4ef0-9f77-5d44826c3734</webElementGuid>
   </webElementProperties>
</WebElementEntity>
