<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_delete_icon</name>
   <tag></tag>
   <elementGuidId>312e3041-c5d0-4413-9956-f92e567c3756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id,'btndelete')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[contains(@id,'btndelete')]</value>
      <webElementGuid>4786c7eb-8ae4-4f1b-a34b-f984a0422267</webElementGuid>
   </webElementProperties>
</WebElementEntity>
