<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_delete_detail</name>
   <tag></tag>
   <elementGuidId>b0f9e24e-7426-453b-88d7-5f487607c24f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;btndeleteopenmodal&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;btndeleteopenmodal&quot;]</value>
      <webElementGuid>ffa114f0-937d-4f9e-a07a-e8b1568b2826</webElementGuid>
   </webElementProperties>
</WebElementEntity>
