<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_reason_name</name>
   <tag></tag>
   <elementGuidId>7b213b6b-3ffc-441f-b0ec-32f1f60dd765</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tslreasonname&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tslreasonname&quot;]</value>
      <webElementGuid>944753ef-b78b-4d19-8865-03e86b4ff87f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
