<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_reason_code</name>
   <tag></tag>
   <elementGuidId>8a808a00-2ec2-4398-bd1f-7d74d419412c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tslreasoncode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tslreasoncode&quot;]</value>
      <webElementGuid>d2a3e5c1-b3eb-43ae-b153-768b0b399256</webElementGuid>
   </webElementProperties>
</WebElementEntity>
