<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_revisit_by_salesco_detail</name>
   <tag></tag>
   <elementGuidId>e5828377-9563-4956-9bd1-074684407eb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;lblreasonissalesconeed&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;lblreasonissalesconeed&quot;]</value>
      <webElementGuid>dc00125f-6954-4fde-ab9f-6183c392cd53</webElementGuid>
   </webElementProperties>
</WebElementEntity>
