<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_reason_name_detail</name>
   <tag></tag>
   <elementGuidId>eb8a20a5-9104-4e8c-b9bb-852c5f1ebe37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;lblreasonname&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;lblreasonname&quot;]</value>
      <webElementGuid>0888adcb-8ed1-40f3-99e0-2249a333c537</webElementGuid>
   </webElementProperties>
</WebElementEntity>
