<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_reason_code_list</name>
   <tag></tag>
   <elementGuidId>474e59b8-3b8d-4c95-9ded-39ed1e84a1b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tblreason&quot;]/tbody/tr/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tblreason&quot;]/tbody/tr/td[1]</value>
      <webElementGuid>08877991-4258-44eb-a3e6-5c5b0f11655b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
