<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_success</name>
   <tag></tag>
   <elementGuidId>c8e90b5d-0c77-4ad7-951c-ed8cf6aedb44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div/div[2]/div/div[2]/div/div[2][count(. | //*[(text() = 'Success' or . = 'Success')]) = count(//*[(text() = 'Success' or . = 'Success')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div/div[2]/div/div[2]/div/div[2]</value>
      <webElementGuid>59ac5193-72e4-46aa-8d1b-cfd7965e06ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Success</value>
      <webElementGuid>f90a9757-d0a9-46d0-8879-2118dee925a5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
