<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>page_limit_list</name>
   <tag></tag>
   <elementGuidId>a89837e3-0e9d-419b-a942-a3fc9bd6cbe8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;contentWrapper&quot;]/div[2]/div[2]/div[2]/div/div[1]/div/div/div/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;contentWrapper&quot;]/div[2]/div[2]/div[2]/div/div[1]/div/div/div/div/span[2]</value>
      <webElementGuid>90aab7f1-14cb-4790-b277-9fc2c8b67db0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
